@baseUrl=http://localhost:8000/api/v1/addresses
@addressId=6a7c2ad3f389f6ed96dc98e5

### create address

POST {{baseUrl}}
Content-Type: application/json

{
    "location": "https://share.google/UCp92LzP4tQFfHXke",
    "region": "Al-Batinah",
    "city": "Masnaah"
}

### list addresses

GET {{baseUrl}}

### get address by id

GET {{baseUrl}}/{{addressId}}

### update address

PATCH {{baseUrl}}/{{addressId}}
Content-Type: application/json

{
    "location": "https://maps.app.goo.gl/Ly51Sz3Zp5JpLqyS9",
    "region": "Al-batinah",
    "city": "AboAbali"
}

### delete address

DELETE {{baseUrl}}/{{addressId}}

#   location: { type: String, required: true },
#   region: { type: String, required: true },
#   city: { type: String, required: true },