
@baseUrl = http://localhost:8000/api/v1/auth

### register a new user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "firstName": "TEST",
  "lastName": "CHECKER",
  "email": "test2@test.test",
  "phoneNumber": "1234567890",
  "companyName": "TEST COMPANY",
  "password": "testpassword"
}

### login with the registered user
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test2@test.test",
  "password": "testpassword"
}

###

@accessToken = {{login.response.body.accessToken}}

### me
GET {{baseUrl}}/me
Authorization: Bearer {{accessToken}}

