@baseUrl=http://localhost:8000/api/v1/batches
@batchId=6a86e28d5cd9e412c490d787
@shipmentId="6a86dd905cd9e412c490d781"

### create batch

POST {{baseUrl}}
Content-Type: application/json

{
    "shipment_ref": {{shipmentId}},
    "deliveryDate": "2026-08-28T14:30:00Z",
    "region": "Abatinah",
    "assignedDriver": {
        "name": "AzizG",
        "phone": "91149027"
    }
}

### list batches

GET {{baseUrl}}

### get batch by id

GET {{baseUrl}}/{{batchId}}

### update batch

PATCH {{baseUrl}}/{{batchId}}
Content-Type: application/json

{
    "assignedDriver": {
        "name": "AboNabil",
        "phone": "91149027"
    }
}

### delete batch

DELETE {{baseUrl}}/{{batchId}}

# const distributionBatchSchema = new Schema<DistributionBatch>({
#   shipment_ref: {
#     type: Types.ObjectId,
#     ref: 'Shipment',
#     required: true,
#   },
#   deliveryDate: {
#     type: Date,
#     required: true,
#   },
#   region: {
#     type: String,
#     required: true,
#   },
#   assignedDriver: {
#     type: {
#       name: String,
#       phone: String,
#     },
#     required: true,
#   },
# });

# export const couldBeUpdated = ['deliveryDate', 'assignedDriver'];