@baseUrl=http://localhost:8000/api/v1/shipments
@shipmentId=6a86dd905cd9e412c490d781
@poolId="6a8136f57464a01bfe7222c8"

### create shipment

POST {{baseUrl}}
Content-Type: application/json

{
    "pool_ref": {{poolId}},
    "preparedQuantity": 800,
    "expectedReadyDate": "2026-08-28T15:30:00Z"
}

### list shipmentes

GET {{baseUrl}}

### get shipment by id

GET {{baseUrl}}/{{shipmentId}}

### update shipment

PATCH {{baseUrl}}/{{shipmentId}}
Content-Type: application/json

{
    "preparedQuantity": 850,
    "expectedReadyDate": "2026-08-28T18:30:00Z"
}

### delete shipment

DELETE {{baseUrl}}/{{shipmentId}}

# const shipmentSchema = new Schema<Shipment>(
#   {
#     pool_ref: {
#       type: Types.ObjectId,
#       ref: 'Pool',
#       required: true,
#     },
#     preparedQuantity: {
#       type: Number,
#       min: 1,
#       max: 1000,
#       required: true,
#     },
#     expectedReadyDate: {
#       type: Date,
#       required: true,
#     },
#     actualReadyDate: {
#       type: Date,
#       default: 'Not Set',
#     },
#     pickUpDate: {
#       type: Date,
#       default: 'Not Set',
#     },
#     pickedUpAt: {
#       type: Date,
#       default: 'No Set',
#     },
#     status: {
#       type: String,
#       enum: [
#         'PREPARATION',
#         'READY_FOR_PICKUP',
#         'PICKED_UP',
#         'DISTRIBUTING',
#         'COMPLETED',
#       ],
#       default: 'PREPARATION',
#     },
#     notes: {
#       type: String,
#     },
#   },
#   {
#     timestamps: true,
#   }
# );

# export const couldBeUpdated = ['preparedQuantity', 'expectedReadyDate'];
