@baseUrl=http://localhost:8000/api/v1/payouts
@payoutID=REPLACE_WITH_PAYOUT_ID
@poolId=REPLACE_WITH_POOL_ID

# This route has no auth/role checks wired up yet.

### create payout

POST {{baseUrl}}
Content-Type: application/json

{
    "pool_ref": "{{poolId}}",
    "grossAmount": 350,
    "platformCommission": 30,
    "netAmount": 350
}

### list payoutes

GET {{baseUrl}}

### get payout by id

GET {{baseUrl}}/{{payoutID}}

### delete payout

DELETE {{baseUrl}}/{{payoutID}}
